### ISSUE TITLE
Can't create new account 

### ISSUE THREAD

**Issue by avinal** [swdotcom/swdc-vscode#10]
I am trying to create a new account but it doesn't work, says you already have associated account with this email address
![image](https://user-images.githubusercontent.com/42297946/53079936-8bf62980-351d-11e9-871f-deaf95614f44.png)

**Comment by mrkhew** [comment]
I'm having the same issue lol, wasted 30 minutes to set it up, it's so difficult.

**Comment by JMac2097** [comment]
Having the same issue here too

**Comment by andrewhli** [comment]
Hi everyone, we’re so sorry for wasting your time. Our goal is to help devs save time! This is related to an issue in yesterday's release. We're fixing the bug right now. In appreciation for your time, could we send you a Software hoodie? Email me at andrew@software.com with a good delivery address, and we'll send that out straightforwardly

**Comment by andrewhli** [comment]
Hi there. Sorry again for wasting your time. We've pushed a fix to the account creation bug. To use the fix, here are the steps:

1. Reset the connection by deleting the .software folder in the home directory on your OS filesystem (image attached).
2. On VS Code, click on Code Time in the status bar, and select "log in" via the dropdown menu.
3. Enter in your preferred email address or use Oauth to connect. If you input your own email address, click on the confirmation link in your inbox. To prevent problems, please ignore any previous confirmation emails, since those will have an expired link.

Previously, the database deleted the email, which made the log in impossible, but we've fixed that. If you experience any other difficulties, please let us know.

**Comment by andrewhli** [comment]
<img width="719" alt="screen shot 2019-02-20 at 10 18 31 am" src="https://user-images.githubusercontent.com/5068143/53115736-cfd83700-34fb-11e9-8f3f-dc8bc23c76ae.png">

**Comment by mrkhew** [comment]
May I know where do I find .software in Windows?

**Comment by andrewhli** [comment]
Hi mrkhew - We released a new feature today where the .software folder no longer needs to be deleted to reset the connection, so hopefully no one else will have to do this going forward. To answer your question, the .software folder in Windows should be in <root>\Users\<username>\.software

**Comment by andrewhli** [comment]
Hey @avinal, @mrkhew, and @JMac2097 - we're live on Product Hunt! Would appreciate any support you can give: https://www.producthunt.com/posts/code-time

**Comment by eteisman** [comment]
Does even remotely work.

It wants me to login, but there is no register button.
So I just select an account, but it says it cannot find my account.

But the only way to 'register' is to install the plugin which is already installed.
Which then wants me to login, except I cannot login, and there is still no way to register an account.
Then it wants me to install a plugin ... again.

No idea how this software is supposed to work, but I am sure that is absolutely does not work.

Weirdest software ever! WTF
