### ISSUE TITLE
One Account Between Multiple PCs

### ISSUE THREAD

**Issue by NetworkMonk** [swdotcom/swdc-vscode#18]
Hi, I seem to be running into a problem quite frequently at the moment.
I code on two machines and would like to use one code time account so that I can make the most of the work / home balance.

It seems like every time I swap machines, I need to log in through VS code again, whenever I do this, it zeros off any stats collected on that machine for the day. So if I don't login to code time until the end of the day, my stats will display as 0min both locally and on the web dashboard.

Anyone else come across this?

Using VSCode on Win10 on both machines, nothing else really different about the machines. I use a software.com account to log in.

**Comment by andrewhli** [comment]
Thanks for letting us know! Yes, one account on multiple PCs is a feature that we should support with 0 problems. We'll be sure to get this fixed for you. We believe this bug is related to a new feature last week that allows one user to have multiple Code Time accounts on one device (enabled a Log Out option). Right now, it looks like those features are creating problems (always showing 0 min coding for some users). We are fixing this today/tomorrow by going back to a simpler version without those extra features.

**Comment by brettmstevens7** [comment]
Hi @NetworkMonk - would you be able to test if you are now able to log in on multiple machines using the same account with the latest version (v11.9)?

**Comment by NetworkMonk** [comment]
@brettmstevens7 Will do - bear with me, just starting my work day now, updated and logged in OK. Will see on my other machine later on today, thanks.

**Comment by NetworkMonk** [comment]
@brettmstevens7 it all appears to be working so far, switched back to my work machine today and stats all make sense, so far so good.

**Comment by brettmstevens7** [comment]
Thanks @NetworkMonk! I'll close this issue then, and if you run into any other issues let me know.
