### ISSUE TITLE
how to change timezone

### ISSUE THREAD

**Issue by zx06** [swdotcom/swdc-vscode#37]
how to change timezone

**Comment by EricChen1248** [comment]
Yes, this is a function thats sorely missed. Code Time "Today" and "Yesterday" are basically uselss without a timezone function, since they're all processed wrong

**Comment by brettmstevens7** [comment]
@EricChen1248 - are you noticing incorrect times in your editor or in the web app?

**Comment by opusmagna** [comment]
I am experiencing the same issue. @brettmstevens7 it is hard to tell. On web app I can not see the 8th of April which is today. And vaguely, the summary in vs-code does not reflect the true values. 

![image](https://user-images.githubusercontent.com/33766678/78820504-994fcb00-79e0-11ea-9510-5d7a710be4dc.png)

---
This is pretty absurd - it 9:36pm at the moment, and i did more work than this today already.
And since I can not predict the logic that runs behind, I can not really spot the reason why this is happening. 
Please note that I am based in Cyprus / timezone GMT +3.

**Comment by brettmstevens7** [comment]
@opusmagna can you check your times again now using the latest (v2.1.72)? We made a number of fixes and improvements this week.

**Comment by opusmagna** [comment]
@brettmstevens7 thank you for the acknowledgement. For the benefit of all, I will check and get back immediately. I need approximately 18 hours :)

**Comment by opusmagna** [comment]
I have checked right now, the active code time did not reset at 9:00 pm as it did before. I will keep checking further to provide more information.

**Comment by EricChen1248** [comment]
> 
> 
> @EricChen1248 - are you noticing incorrect times in your editor or in the web app?

Sorry about the delay, forgot to check notifications. It used to be the web app times was off by my timezone. It seems to be correct now.

**Comment by bjacobson26** [comment]
This is in our backlog. Thank you!
