### ISSUE TITLE
Correct code time not showing

### ISSUE THREAD

**Issue by aneesafatima** [swdotcom/swdc-vscode#488]
Code time showing is lesser than the actual time spent on coding on vs code

**Comment by xavluiz** [comment]
> Code time showing is lesser than the actual time spent on coding on vs code

Hi @aneesa04,
Thank you for the issue comment. Just to confirm, are you referring to the time that is shown in the vscode statusbar? That number is the "Active Code Time" vs the "Code Time". Your code time is the total time you have spent in your editor today and your active code time is the time you spend actively writing and editing code in your editor or IDE. Thanks.

**Comment by aneesa04** [comment]
Actually both are lesser than actual time. I have been facing this problem
since yesterday only

**Comment by mmclead** [comment]
Hello.   Can you provide a screen shot or more context for this?   Are you comparing the time shown in the web app compared to what's reported in the editor ?

**Comment by ZeroCore-Zero** [comment]
I have this problem either, and it went on for such a long time, nearly since I installed it.
For example, today I work from about 10:00am to 16:00am. I had glanced to the status bar at noon and it shown about 2 hours. However, when I finished my work, I found it turned into 23m. I opened dashboard and found both the active time and code time are become 23m.
That's strange, I think.

**Comment by mmclead** [comment]
Hello.

We are looking into this now.    Thank you for the reports, they are helpful to pinpoint the display issues.

**Comment by bjacobson26** [comment]
This should be resolved. Please reopen if you are still experiencing issues. Thank you.
