### ISSUE TITLE
Web Dashboard "An Error Occurred"

### ISSUE THREAD

**Issue by roguesleipnir** [swdotcom/swdc-vscode#57]
I tried visiting https://app.software.com/ from the extension link, Chrome, Firefox, Edge, even on mobile browsers.
It flashes the dashboard for a second then goes to a white screen with "An Error Occurred".
I logged in with my github account.

**Comment by andrewhli** [comment]
Hi @roguesleipnir - We had a database process that took up too much resources and made the application inaccessible. We believe this is fixed. However, if you're still seeing "An Error Occurred", could you email cody@software.com with the GitHub email address you're using to log in? We can make sure the issue is fixed for you

**Comment by roguesleipnir** [comment]
Ok, I'll send an email since I'm still experiencing the bug.

**Comment by andrewhli** [comment]
We believe this problem is fixed. Please email cody@software.com if you see any other problems. Happy to help. Thank you.
